# Generated by Django 3.2.4 on 2021-07-05 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='location_name',
        ),
    ]
