# Generated by Django 3.2.4 on 2021-07-05 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20210705_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(default=3, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='location_name',
            field=models.CharField(default=4, max_length=255),
            preserve_default=False,
        ),
    ]
