# Generated by Django 3.2.4 on 2021-07-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20210705_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='author',
            field=models.CharField(default='Admin', max_length=250),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=67),
        ),
    ]
