# Generated by Django 3.2.4 on 2021-07-04 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='images',
        ),
    ]
