# Generated by Django 3.2.4 on 2021-07-04 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_rename_image_image_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='images',
            new_name='image',
        ),
    ]
